/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.sp.senac.e169.lojainformatica;

import java.util.List;
import javax.swing.DefaultBoundedRangeModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author patrick.spereira1
 */
public class tellVendaPC extends javax.swing.JFrame {

    /**
     * Creates new form tellVendaPC
     */
    public tellVendaPC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgtipopc = new javax.swing.ButtonGroup();
        bgso = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        rbopc = new javax.swing.JRadioButton();
        rbonot = new javax.swing.JRadioButton();
        rboserv = new javax.swing.JRadioButton();
        tgwin = new javax.swing.JToggleButton();
        tglin = new javax.swing.JToggleButton();
        cbohd = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        chkmochila = new javax.swing.JCheckBox();
        chkmouse = new javax.swing.JCheckBox();
        chkteclado = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstgarantias = new javax.swing.JList<>();
        btnadicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpc = new javax.swing.JTable();
        btndetalhes = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        bgtipopc.add(rbopc);
        rbopc.setText("pc");

        bgtipopc.add(rbonot);
        rbonot.setText("not");

        bgtipopc.add(rboserv);
        rboserv.setText("serv");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbopc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbonot)
                .addGap(121, 121, 121)
                .addComponent(rboserv)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbopc)
                    .addComponent(rbonot)
                    .addComponent(rboserv))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bgso.add(tgwin);
        tgwin.setText("Win");

        bgso.add(tglin);
        tglin.setText("Lin");

        cbohd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo de HD...", "HD 1TB HDD\t", "HD 256GB SSD", "HD 512GB SSD", "HD 1TB SSD" }));
        cbohd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbohdActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 204));

        chkmochila.setText("mochila");

        chkmouse.setText("mouse gamer");

        chkteclado.setText(" teclado gamer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(chkmochila)
                .addGap(35, 35, 35)
                .addComponent(chkmouse)
                .addGap(27, 27, 27)
                .addComponent(chkteclado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkmochila)
                    .addComponent(chkmouse)
                    .addComponent(chkteclado))
                .addGap(14, 14, 14))
        );

        lstgarantias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "roubo", "incendio", "queda", "perda", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstgarantias);

        btnadicionar.setText("adicionar");
        btnadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadicionarActionPerformed(evt);
            }
        });

        tblpc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo", "so", "hd", "acessorios", "garantias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblpc);

        btndetalhes.setText("detalhes");
        btndetalhes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetalhesActionPerformed(evt);
            }
        });

        btnexcluir.setText("excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(cbohd, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tgwin, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tglin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnadicionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgwin)
                    .addComponent(tglin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbohd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btndetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnexcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbohdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbohdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbohdActionPerformed

    private void btnadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadicionarActionPerformed

        String tipopc = "";

        if (rbopc.isSelected()) {

            tipopc = rbopc.getText();
        } else if (rbonot.isSelected()) {
            tipopc = rbonot.getText();
        } else if (rboserv.isSelected()) {
            tipopc = rboserv.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo de compitador");
        }

        //Sistema Operacional
        String tipoSo = "";

        if (tgwin.isSelected()) {
            tipoSo = tgwin.getText();
        } else if (tglin.isSelected()) {
            tipoSo = tglin.getText();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um sistema Operacional");
        }

        //HD
        String hd = cbohd.getSelectedItem().toString();

        //Acessórios
        String acessorios = "";

        if (chkmochila.isSelected()) {
            acessorios += chkmochila.getText() + ", ";
        }

        if (chkmouse.isSelected()) {
            acessorios += chkmochila.getText() + ", ";
        }

        if (chkteclado.isSelected()) {
            acessorios += chkmochila.getText() + ", ";
        }

        //Garantias
        List<String> garantiasSelecionadas;

        garantiasSelecionadas = lstgarantias.getSelectedValuesList();
        
        String garantiasConcatenadas  ="";

        for (String garantia : garantiasSelecionadas) {
            garantiasConcatenadas += garantia;
        }

        //finalmente .. Adicionar as Opções Selecionadas À TABLEA
        DefaultTableModel modelo = (DefaultTableModel) tblpc.getModel();
        
        //Adicionado uma linha a tabela
        
        modelo.addRow(new String[]{
            tipopc,
            tipoSo,
             hd,
             acessorios,
             garantiasConcatenadas
        });
    }//GEN-LAST:event_btnadicionarActionPerformed

    private void btndetalhesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetalhesActionPerformed
        int linhaSelecionada  = tblpc.getSelectedRow();
        
        if(linhaSelecionada >=0){
            //Exibos os detalhes da linha
            
            JOptionPane.showMessageDialog(rootPane,"Dados do Item: \n"+
                    tblpc.getValueAt(linhaSelecionada, 0) + "\n"+
                    tblpc.getValueAt(linhaSelecionada, 1) + "\n"+
                    tblpc.getValueAt(linhaSelecionada, 2) + "\n"+
                    tblpc.getValueAt(linhaSelecionada, 3) + "\n"+
                    tblpc.getValueAt(linhaSelecionada, 4) + "\n"
                    );
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha ");
        }
        
        
        
    }//GEN-LAST:event_btndetalhesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tellVendaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tellVendaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tellVendaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tellVendaPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tellVendaPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgso;
    private javax.swing.ButtonGroup bgtipopc;
    private javax.swing.JButton btnadicionar;
    private javax.swing.JButton btndetalhes;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JComboBox<String> cbohd;
    private javax.swing.JCheckBox chkmochila;
    private javax.swing.JCheckBox chkmouse;
    private javax.swing.JCheckBox chkteclado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstgarantias;
    private javax.swing.JRadioButton rbonot;
    private javax.swing.JRadioButton rbopc;
    private javax.swing.JRadioButton rboserv;
    private javax.swing.JTable tblpc;
    private javax.swing.JToggleButton tglin;
    private javax.swing.JToggleButton tgwin;
    // End of variables declaration//GEN-END:variables
}
